version: '3.8'
services:
  db:
    image: postgres:15.1-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
